# coding: utf-8

"""
    Product API

    Simple API for managing products based on the OpenAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.products_api import ProductsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self):
        self.api = ProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_products_get(self):
        """Test case for api_v1_products_get

        Returns list of all products  # noqa: E501
        """
        pass

    def test_api_v1_products_id_delete(self):
        """Test case for api_v1_products_id_delete

        Delete product using id  # noqa: E501
        """
        pass

    def test_api_v1_products_id_get(self):
        """Test case for api_v1_products_id_get

        Getting product by id  # noqa: E501
        """
        pass

    def test_api_v1_products_id_patch(self):
        """Test case for api_v1_products_id_patch

        Edit a product using id  # noqa: E501
        """
        pass

    def test_api_v1_products_id_put(self):
        """Test case for api_v1_products_id_put

        Edit a product using id  # noqa: E501
        """
        pass

    def test_api_v1_products_post(self):
        """Test case for api_v1_products_post

        Creates a new product  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
