# coding: utf-8

"""
    Product API

    Simple API for managing products based on the OpenAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.product_patch_request import ProductPatchRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestProductPatchRequest(unittest.TestCase):
    """ProductPatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductPatchRequest(self):
        """Test ProductPatchRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.product_patch_request.ProductPatchRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
