services:
  api-gateway:
    build: .
    ports:
      - "5000:5000"
  counter_service:
    build: ./counter_service/
  # ports:
  #     - "8000:5000"
  user_service:
    build: ./user_service/

  redis:
    image: "redis:alpine"

  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

 # grafana:
  #   image: 
