# coding: utf-8

"""
    Product API

    Simple API for managing products based on the OpenAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProductResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'description': 'str',
        'price': 'float',
        'sku': 'str',
        'quantity': 'int',
        'created_at': 'int',
        'updated_at': 'int'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'price': 'price',
        'sku': 'sku',
        'quantity': 'quantity',
        'created_at': 'created_at',
        'updated_at': 'updated_at'
    }

    def __init__(self, id=None, name=None, description=None, price=None, sku=None, quantity=None, created_at=None, updated_at=None):  # noqa: E501
        """ProductResponse - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._description = None
        self._price = None
        self._sku = None
        self._quantity = None
        self._created_at = None
        self._updated_at = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if price is not None:
            self.price = price
        if sku is not None:
            self.sku = sku
        if quantity is not None:
            self.quantity = quantity
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def id(self):
        """Gets the id of this ProductResponse.  # noqa: E501

        Product's id, autoincrement  # noqa: E501

        :return: The id of this ProductResponse.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProductResponse.

        Product's id, autoincrement  # noqa: E501

        :param id: The id of this ProductResponse.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ProductResponse.  # noqa: E501

        Product's name  # noqa: E501

        :return: The name of this ProductResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProductResponse.

        Product's name  # noqa: E501

        :param name: The name of this ProductResponse.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this ProductResponse.  # noqa: E501

        Product's description  # noqa: E501

        :return: The description of this ProductResponse.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ProductResponse.

        Product's description  # noqa: E501

        :param description: The description of this ProductResponse.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def price(self):
        """Gets the price of this ProductResponse.  # noqa: E501

        Product's price  # noqa: E501

        :return: The price of this ProductResponse.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this ProductResponse.

        Product's price  # noqa: E501

        :param price: The price of this ProductResponse.  # noqa: E501
        :type: float
        """

        self._price = price

    @property
    def sku(self):
        """Gets the sku of this ProductResponse.  # noqa: E501

        Product's sku  # noqa: E501

        :return: The sku of this ProductResponse.  # noqa: E501
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku):
        """Sets the sku of this ProductResponse.

        Product's sku  # noqa: E501

        :param sku: The sku of this ProductResponse.  # noqa: E501
        :type: str
        """

        self._sku = sku

    @property
    def quantity(self):
        """Gets the quantity of this ProductResponse.  # noqa: E501

        Product's quantity  # noqa: E501

        :return: The quantity of this ProductResponse.  # noqa: E501
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this ProductResponse.

        Product's quantity  # noqa: E501

        :param quantity: The quantity of this ProductResponse.  # noqa: E501
        :type: int
        """

        self._quantity = quantity

    @property
    def created_at(self):
        """Gets the created_at of this ProductResponse.  # noqa: E501

        When the product was added to database  # noqa: E501

        :return: The created_at of this ProductResponse.  # noqa: E501
        :rtype: int
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ProductResponse.

        When the product was added to database  # noqa: E501

        :param created_at: The created_at of this ProductResponse.  # noqa: E501
        :type: int
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this ProductResponse.  # noqa: E501

        When the product was last modified  # noqa: E501

        :return: The updated_at of this ProductResponse.  # noqa: E501
        :rtype: int
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ProductResponse.

        When the product was last modified  # noqa: E501

        :param updated_at: The updated_at of this ProductResponse.  # noqa: E501
        :type: int
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
