# coding: utf-8

# flake8: noqa

"""
    Product API

    Simple API for managing products based on the OpenAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.products_api import ProductsApi
from swagger_client.api.default_api import DefaultApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.error import Error
from swagger_client.models.product_create_request import ProductCreateRequest
from swagger_client.models.product_patch_request import ProductPatchRequest
from swagger_client.models.product_response import ProductResponse
