# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProductResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, description: str=None, price: float=None, sku: str=None, quantity: int=None, created_at: int=None, updated_at: int=None):  # noqa: E501
        """ProductResponse - a model defined in Swagger

        :param id: The id of this ProductResponse.  # noqa: E501
        :type id: int
        :param name: The name of this ProductResponse.  # noqa: E501
        :type name: str
        :param description: The description of this ProductResponse.  # noqa: E501
        :type description: str
        :param price: The price of this ProductResponse.  # noqa: E501
        :type price: float
        :param sku: The sku of this ProductResponse.  # noqa: E501
        :type sku: str
        :param quantity: The quantity of this ProductResponse.  # noqa: E501
        :type quantity: int
        :param created_at: The created_at of this ProductResponse.  # noqa: E501
        :type created_at: int
        :param updated_at: The updated_at of this ProductResponse.  # noqa: E501
        :type updated_at: int
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'description': str,
            'price': float,
            'sku': str,
            'quantity': int,
            'created_at': int,
            'updated_at': int
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'price': 'price',
            'sku': 'sku',
            'quantity': 'quantity',
            'created_at': 'created_at',
            'updated_at': 'updated_at'
        }
        self._id = id
        self._name = name
        self._description = description
        self._price = price
        self._sku = sku
        self._quantity = quantity
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'ProductResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductResponse of this ProductResponse.  # noqa: E501
        :rtype: ProductResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this ProductResponse.

        Product's id, autoincrement  # noqa: E501

        :return: The id of this ProductResponse.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ProductResponse.

        Product's id, autoincrement  # noqa: E501

        :param id: The id of this ProductResponse.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this ProductResponse.

        Product's name  # noqa: E501

        :return: The name of this ProductResponse.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ProductResponse.

        Product's name  # noqa: E501

        :param name: The name of this ProductResponse.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this ProductResponse.

        Product's description  # noqa: E501

        :return: The description of this ProductResponse.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ProductResponse.

        Product's description  # noqa: E501

        :param description: The description of this ProductResponse.
        :type description: str
        """

        self._description = description

    @property
    def price(self) -> float:
        """Gets the price of this ProductResponse.

        Product's price  # noqa: E501

        :return: The price of this ProductResponse.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this ProductResponse.

        Product's price  # noqa: E501

        :param price: The price of this ProductResponse.
        :type price: float
        """

        self._price = price

    @property
    def sku(self) -> str:
        """Gets the sku of this ProductResponse.

        Product's sku  # noqa: E501

        :return: The sku of this ProductResponse.
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku: str):
        """Sets the sku of this ProductResponse.

        Product's sku  # noqa: E501

        :param sku: The sku of this ProductResponse.
        :type sku: str
        """

        self._sku = sku

    @property
    def quantity(self) -> int:
        """Gets the quantity of this ProductResponse.

        Product's quantity  # noqa: E501

        :return: The quantity of this ProductResponse.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this ProductResponse.

        Product's quantity  # noqa: E501

        :param quantity: The quantity of this ProductResponse.
        :type quantity: int
        """

        self._quantity = quantity

    @property
    def created_at(self) -> int:
        """Gets the created_at of this ProductResponse.

        When the product was added to database  # noqa: E501

        :return: The created_at of this ProductResponse.
        :rtype: int
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: int):
        """Sets the created_at of this ProductResponse.

        When the product was added to database  # noqa: E501

        :param created_at: The created_at of this ProductResponse.
        :type created_at: int
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> int:
        """Gets the updated_at of this ProductResponse.

        When the product was last modified  # noqa: E501

        :return: The updated_at of this ProductResponse.
        :rtype: int
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: int):
        """Sets the updated_at of this ProductResponse.

        When the product was last modified  # noqa: E501

        :param updated_at: The updated_at of this ProductResponse.
        :type updated_at: int
        """

        self._updated_at = updated_at
