# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProductCreateRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, description: str=None, price: float=None, sku: str=None, quantity: int=None):  # noqa: E501
        """ProductCreateRequest - a model defined in Swagger

        :param name: The name of this ProductCreateRequest.  # noqa: E501
        :type name: str
        :param description: The description of this ProductCreateRequest.  # noqa: E501
        :type description: str
        :param price: The price of this ProductCreateRequest.  # noqa: E501
        :type price: float
        :param sku: The sku of this ProductCreateRequest.  # noqa: E501
        :type sku: str
        :param quantity: The quantity of this ProductCreateRequest.  # noqa: E501
        :type quantity: int
        """
        self.swagger_types = {
            'name': str,
            'description': str,
            'price': float,
            'sku': str,
            'quantity': int
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'price': 'price',
            'sku': 'sku',
            'quantity': 'quantity'
        }
        self._name = name
        self._description = description
        self._price = price
        self._sku = sku
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'ProductCreateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductCreateRequest of this ProductCreateRequest.  # noqa: E501
        :rtype: ProductCreateRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ProductCreateRequest.

        Product's name  # noqa: E501

        :return: The name of this ProductCreateRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ProductCreateRequest.

        Product's name  # noqa: E501

        :param name: The name of this ProductCreateRequest.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this ProductCreateRequest.

        Product's description  # noqa: E501

        :return: The description of this ProductCreateRequest.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ProductCreateRequest.

        Product's description  # noqa: E501

        :param description: The description of this ProductCreateRequest.
        :type description: str
        """

        self._description = description

    @property
    def price(self) -> float:
        """Gets the price of this ProductCreateRequest.

        Product's price  # noqa: E501

        :return: The price of this ProductCreateRequest.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this ProductCreateRequest.

        Product's price  # noqa: E501

        :param price: The price of this ProductCreateRequest.
        :type price: float
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def sku(self) -> str:
        """Gets the sku of this ProductCreateRequest.

        Product's sku  # noqa: E501

        :return: The sku of this ProductCreateRequest.
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku: str):
        """Sets the sku of this ProductCreateRequest.

        Product's sku  # noqa: E501

        :param sku: The sku of this ProductCreateRequest.
        :type sku: str
        """

        self._sku = sku

    @property
    def quantity(self) -> int:
        """Gets the quantity of this ProductCreateRequest.

        Product's quantity  # noqa: E501

        :return: The quantity of this ProductCreateRequest.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this ProductCreateRequest.

        Product's quantity  # noqa: E501

        :param quantity: The quantity of this ProductCreateRequest.
        :type quantity: int
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity
